### ISSUE TITLE
public url dead

### ISSUE THREAD

**Issue by kevinlincg** [clarketm/myip#1]
"http://v6.ident.me/" =>This URL is Dead.

**Comment by clarketm** [comment]
@kevinlincg - the URL is valid, but not all networks support ipv6. Please verify that this isn’t the case. http://ipv6-test.com/

**Comment by clarketm** [comment]
Closing because there is not an issue with the URL or CLI tool (i.e. When ipv6 addresses are not available, they will not be shown in the results set).
